image: gitpod/workspace-postgres
ports:
  - port: 3000
    visibility: public
vscode:
  extensions:
    - pinage404.rust-extension-pack
    - bungcip.better-toml
    - hbenl.vscode-test-explorer
    - hbenl.test-adapter-converter
    - rust-lang.rust-analyzer
    - serayuzgur.crates
    - swellaby.vscode-rust-test-adapter
